In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from pylab import rcParams
import seaborn as sb

import scipy 
from scipy.stats import spearmanr

In [2]:
#yellow cabs data - january
yellow_cabs_data = pd.read_csv('Documents/yellow_tripdata_2018-01.csv')

In [3]:
taxi_data = pd.read_csv("Documents/taxi _zone_lookup.csv")
taxi_data

,LocationID,Borough,Zone,service_zone
0,1,EWR,Newark Airport,EWR
1,2,Queens,Jamaica Bay,Boro Zone
2,3,Bronx,Allerton/Pelham Gardens,Boro Zone
3,4,Manhattan,Alphabet City,Yellow Zone
4,5,Staten Island,Arden Heights,Boro Zone
5,6,Staten Island,Arrochar/Fort Wadsworth,Boro Zone
6,7,Queens,Astoria,Boro Zone
7,8,Queens,Astoria Park,Boro Zone
8,9,Queens,Auburndale,Boro Zone
9,10,Queens,Baisley Park,Boro Zone
10,11,Brooklyn,Bath Beach,Boro Zone
11,12,Manhattan,Battery Park,Yellow Zone
12,13,Manhattan,Battery Park City,Yellow Zone
13,14,Brooklyn,Bay Ridge,Boro Zone
14,15,Queens,Bay Terrace/Fort Totten,Boro Zone
15,16,Queens,Bayside,Boro Zone
16,17,Brooklyn,Bedford,Boro Zone
17,18,Bronx,Bedford Park,Boro Zone
18,19,Queens,Bellerose,Boro Zone
19,20,Bronx,Belmont,Boro Zone
20,21,Brooklyn,Bensonhurst East,Boro Zone
21,22,Brooklyn,Bensonhurst West,Boro Zone
22,23,Staten Island,Bloomfield/Emerson Hill,Boro Zone
23,24,Manhattan,Bloomingdale,Yellow Zone
24,25,Brooklyn,Boerum Hill,Boro Zone
25,26,Brooklyn,Borough Park,Boro Zone
26,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
27,28,Queens,Briarwood/Jamaica Hills,Boro Zone
28,29,Brooklyn,Brighton Beach,Boro Zone
29,30,Queens,Broad Channel,Boro Zone
...,...,...,...,...
235,236,Manhattan,Upper East Side North,Yellow Zone
236,237,Manhattan,Upper East Side South,Yellow Zone
237,238,Manhattan,Upper West Side North,Yellow Zone
238,239,Manhattan,Upper West Side South,Yellow Zone
239,240,Bronx,Van Cortlandt Park,Boro Zone
240,241,Bronx,Van Cortlandt Village,Boro Zone
241,242,Bronx,Van Nest/Morris Park,Boro Zone
242,243,Manhattan,Washington Heights North,Boro Zone
243,244,Manhattan,Washington Heights South,Boro Zone
244,245,Staten Island,West Brighton,Boro Zone
245,246,Manhattan,West Chelsea/Hudson Yards,Yellow Zone
246,247,Bronx,West Concourse,Boro Zone
247,248,Bronx,West Farms/Bronx River,Boro Zone
248,249,Manhattan,West Village,Yellow Zone
249,250,Bronx,Westchester Village/Unionport,Boro Zone
250,251,Staten Island,Westerleigh,Boro Zone
251,252,Queens,Whitestone,Boro Zone
252,253,Queens,Willets Point,Boro Zone
253,254,Bronx,Williamsbridge/Olinville,Boro Zone
254,255,Brooklyn,Williamsburg (North Side),Boro Zone
255,256,Brooklyn,Williamsburg (South Side),Boro Zone
256,257,Brooklyn,Windsor Terrace,Boro Zone
257,258,Queens,Woodhaven,Boro Zone
258,259,Bronx,Woodlawn/Wakefield,Boro Zone
259,260,Queens,Woodside,Boro Zone
260,261,Manhattan,World Trade Center,Yellow Zone
261,262,Manhattan,Yorkville East,Yellow Zone
262,263,Manhattan,Yorkville West,Yellow Zone
263,264,Unknown,NV,NaN
264,265,Unknown,NaN,NaN

In [5]:
merged_data=pd.merge(yellow_cabs_data, taxi_data, on = None, left_on = 'PULocationID', right_on = 'LocationID')
df_Jan = pd.DataFrame(merged_data)
df_Jan

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,LocationID,Borough,Zone,service_zone
0,1,2018-01-01 00:21:05,2018-01-01 00:24:23,1,0.50,1,N,41,24,2,...,0.5,0.5,0.00,0.00,0.3,5.80,41,Manhattan,Central Harlem,Boro Zone
1,2,2018-01-01 00:49:32,2018-01-01 00:59:52,1,1.36,1,N,41,74,2,...,0.5,0.5,0.00,0.00,0.3,9.80,41,Manhattan,Central Harlem,Boro Zone
2,1,2018-01-01 00:11:56,2018-01-01 00:14:35,2,0.30,1,N,41,41,2,...,0.5,0.5,0.00,0.00,0.3,5.30,41,Manhattan,Central Harlem,Boro Zone
3,1,2018-01-01 00:58:32,2018-01-01 01:43:45,1,14.10,1,N,41,112,1,...,0.5,0.5,12.10,5.76,0.3,60.66,41,Manhattan,Central Harlem,Boro Zone
4,2,2018-01-01 00:14:09,2018-01-01 00:44:06,1,8.77,1,N,41,223,1,...,0.5,0.5,6.06,0.00,0.3,36.36,41,Manhattan,Central Harlem,Boro Zone
5,2,2018-01-01 00:32:15,2018-01-01 00:35:54,1,0.76,1,N,41,151,1,...,0.5,0.5,1.00,0.00,0.3,7.30,41,Manhattan,Central Harlem,Boro Zone
6,2,2018-01-01 00:38:34,2018-01-01 00:45:19,5,1.06,1,N,41,166,1,...,0.5,0.5,1.00,0.00,0.3,8.80,41,Manhattan,Central Harlem,Boro Zone
7,1,2018-01-01 00:38:54,2018-01-01 00:52:02,1,2.40,1,N,41,244,2,...,0.5,0.5,0.00,0.00,0.3,12.80,41,Manhattan,Central Harlem,Boro Zone
8,1,2018-01-01 00:28:06,2018-01-01 00:32:34,3,1.40,1,N,41,238,1,...,0.5,0.5,2.15,0.00,0.3,9.45,41,Manhattan,Central Harlem,Boro Zone
9,1,2018-01-01 00:36:18,2018-01-01 00:41:33,3,0.90,1,N,41,42,1,...,0.5,0.5,2.00,0.00,0.3,8.80,41,Manhattan,Central Harlem,Boro Zone
10,1,2018-01-01 00:50:29,2018-01-01 01:16:19,2,10.80,1,N,41,174,2,...,0.5,0.5,0.00,0.00,0.3,33.80,41,Manhattan,Central Harlem,Boro Zone
11,1,2018-01-01 00:35:57,2018-01-01 00:45:42,2,2.90,1,N,41,239,1,...,0.5,0.5,2.35,0.00,0.3,14.15,41,Manhattan,Central Harlem,Boro Zone
12,2,2018-01-01 00:44:14,2018-01-01 01:11:50,6,11.06,1,N,41,18,2,...,0.5,0.5,0.00,2.64,0.3,37.44,41,Manhattan,Central Harlem,Boro Zone
13,1,2018-01-01 00:48:29,2018-01-01 01:15:08,4,4.80,1,N,41,229,2,...,0.5,0.5,0.00,0.00,0.3,21.30,41,Manhattan,Central Harlem,Boro Zone
14,2,2018-01-01 00:21:32,2018-01-01 00:57:10,1,8.98,1,N,41,114,1,...,0.5,0.5,6.76,0.00,0.3,40.56,41,Manhattan,Central Harlem,Boro Zone
15,1,2018-01-01 00:48:28,2018-01-01 01:00:07,1,2.00,1,N,41,168,2,...,0.5,0.5,0.00,0.00,0.3,11.80,41,Manhattan,Central Harlem,Boro Zone
16,1,2018-01-01 00:47:55,2018-01-01 00:57:58,1,2.10,1,N,41,116,2,...,0.5,0.5,0.00,0.00,0.3,10.80,41,Manhattan,Central Harlem,Boro Zone
17,1,2018-01-01 00:07:30,2018-01-01 00:16:22,3,1.40,1,N,41,151,2,...,0.5,0.5,0.00,0.00,0.3,8.80,41,Manhattan,Central Harlem,Boro Zone
18,2,2018-01-01 00:14:29,2018-01-01 00:21:52,1,1.63,1,N,41,116,1,...,0.5,0.5,1.00,0.00,0.3,9.80,41,Manhattan,Central Harlem,Boro Zone
19,2,2018-01-01 00:25:04,2018-01-01 00:31:42,5,1.22,1,N,41,42,1,...,0.5,0.5,1.56,0.00,0.3,9.36,41,Manhattan,Central Harlem,Boro Zone
20,1,2018-01-01 00:04:04,2018-01-01 00:14:45,2,2.40,1,N,41,239,2,...,0.5,0.5,0.00,0.00,0.3,11.80,41,Manhattan,Central Harlem,Boro Zone
21,1,2018-01-01 00:47:48,2018-01-01 01:01:45,1,2.70,1,N,41,143,2,...,0.5,0.5,0.00,0.00,0.3,13.30,41,Manhattan,Central Harlem,Boro Zone
22,2,2018-01-01 00:17:35,2018-01-01 00:23:23,5,1.01,1,N,41,151,1,...,0.5,0.5,1.70,0.00,0.3,9.00,41,Manhattan,Central Harlem,Boro Zone
23,2,2018-01-01 01:00:37,2018-01-01 01:08:58,1,1.72,1,N,41,42,2,...,0.5,0.5,0.00,0.00,0.3,9.30,41,Manhattan,Central Harlem,Boro Zone
24,2,2018-01-01 00:51:38,2018-01-01 00:57:32,6,1.18,1,N,41,166,2,...,0.5,0.5,0.00,0.00,0.3,7.80,41,Manhattan,Central Harlem,Boro Zone
25,1,2018-01-01 00:54:47,2018-01-01 01:04:20,1,1.60,1,N,41,42,2,...,0.5,0.5,0.00,0.00,0.3,10.30,41,Manhattan,Central Harlem,Boro Zone
26,2,2018-01-01 00:45:16,2018-01-01 00:55:10,1,2.00,1,N,41,116,1,...,0.5,0.5,0.00,0.00,0.3,10.30,41,Manhattan,Central Harlem,Boro Zone
27,2,2018-01-01 00:11:39,2018-01-01 00:17:27,2,1.24,1,N,41,74,2,...,0.5,0.5,0.00,0.00,0.3,7.80,41,Manhattan,Central Harlem,Boro Zone
28,2,2018-01-01 00:50:15,2018-01-01 00:52:46,2,0.49,1,N,41,41,2,...,0.5,0.5,0.00,0.00,0.3,5.30,41,Manhattan,Central Harlem,Boro Zone
29,1,2018-01-01 00:54:23,2018-01-01 01:03:32,2,1.50,1,N,41,74,2,...,0.5,0.5,0.00,0.00,0.3,9.80,41,Manhattan,Central Harlem,Boro Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8759844,1,2018-01-30 07:37:45,2018-01-30 07:37:52,1,0.00,1,Y,109,109,1,...,0.0,0.5,0.00,0.00,0.3,3.30,109,Staten Island,Great Kills,Boro Zone
8759845,1,2018-01-30 07:42:55,2018-01-30 07:43:42,1,0.00,5,Y,109,109,3,...,0.0,0.0,0.00,0.00,0.3,116.80,109,Staten Island,Great Kills,Boro Zone
8759846,2,2018-01-07 17:42:13,2018-01-07 17:42:36,1,0.00,5,N,115,115,1,...,0.0,0.5,15.00,0.00,0.3,240.80,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759847,2,2018-01-12 11:49:06,2018-01-12 12:10:59,1,0.43,1,N,115,115,2,...,0.0,0.5,0.00,0.00,0.3,14.30,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759848,2,2018-01-14 19:11:43,2018-01-14 19:11:58,1,0.00,5,N,115,115,1,...,0.0,0.0,0.00,0.00,0.3,130.30,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759849,2,2018-01-14 19:43:24,2018-01-14 19:45:00,2,0.00,1,N,115,115,2,...,0.0,0.5,0.00,0.00,0.3,3.80,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759850,2,2018-01-15 05:44:01,2018-01-15 05:54:36,1,6.32,1,N,115,11,2,...,0.5,0.5,0.00,0.00,0.3,20.30,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759851,2,2018-01-19 21:19:30,2018-01-19 21:28:09,5,2.90,1,N,115,214,2,...,0.5,0.5,0.00,0.00,0.3,11.80,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759852,2,2018-01-21 18:14:41,2018-01-21 19:08:32,1,0.00,1,N,115,115,1,...,0.0,0.5,8.94,0.00,0.3,38.74,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759853,2,2018-01-07 18:02:56,2018-01-07 18:03:18,1,0.19,1,N,184,184,2,...,0.0,0.5,0.00,0.00,0.3,3.30,184,Bronx,Pelham Bay Park,Boro Zone
8759854,1,2018-01-28 21:14:55,2018-01-28 21:39:54,1,14.60,1,N,184,233,4,...,0.5,0.5,0.00,0.00,0.3,41.30,184,Bronx,Pelham Bay Park,Boro Zone
8759855,2,2018-01-07 20:20:39,2018-01-07 20:20:47,1,0.00,5,N,245,245,1,...,0.0,0.0,15.06,0.00,0.3,90.36,245,Staten Island,West Brighton,Boro Zone
8759856,1,2018-01-15 14:41:58,2018-01-15 15:42:26,1,21.70,1,N,245,236,1,...,0.0,0.5,18.70,11.52,0.3,93.52,245,Staten Island,West Brighton,Boro Zone
8759857,2,2018-01-18 08:53:36,2018-01-18 09:35:51,1,13.06,1,N,245,261,1,...,0.0,0.5,0.00,17.28,0.3,59.08,245,Staten Island,West Brighton,Boro Zone
8759858,2,2018-01-20 07:38:59,2018-01-20 07:39:48,1,0.00,5,N,245,245,1,...,0.0,0.5,18.70,11.52,0.3,81.02,245,Staten Island,West Brighton,Boro Zone
8759859,1,2018-01-25 00:06:23,2018-01-25 00:06:57,1,0.00,5,N,245,245,1,...,0.0,0.0,0.00,0.00,0.3,70.30,245,Staten Island,West Brighton,Boro Zone
8759860,2,2018-01-10 01:13:21,2018-01-10 01:43:30,6,11.77,1,N,221,23,2,...,0.5,0.5,0.00,0.00,0.3,37.80,221,Staten Island,Stapleton,Boro Zone
8759861,2,2018-01-13 02:02:35,2018-01-13 02:02:43,1,0.00,3,N,27,27,2,...,0.5,0.0,0.00,0.00,0.3,20.80,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759862,2,2018-01-13 02:06:33,2018-01-13 02:10:15,1,0.97,1,N,27,27,2,...,0.5,0.5,0.00,0.00,0.3,6.80,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759863,2,2018-01-16 22:03:55,2018-01-16 22:04:25,7,0.00,5,N,27,27,1,...,0.0,0.0,15.06,0.00,0.3,90.36,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759864,2,2018-01-18 23:37:12,2018-01-18 23:46:27,1,2.14,1,N,27,264,1,...,0.5,0.5,2.06,0.00,0.3,12.36,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759865,2,2018-01-27 00:33:55,2018-01-27 00:57:10,2,7.33,1,N,27,210,2,...,0.5,0.5,0.00,2.16,0.3,26.96,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759866,2,2018-01-14 10:49:13,2018-01-14 10:55:44,2,1.75,1,N,105,105,2,...,0.0,0.5,0.00,0.00,0.3,8.30,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759867,2,2018-01-14 11:54:00,2018-01-14 12:05:39,1,1.47,1,N,105,105,1,...,0.0,0.5,1.96,0.00,0.3,11.76,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759868,2,2018-01-15 17:57:10,2018-01-15 18:06:32,1,1.71,1,N,105,79,1,...,0.0,0.5,1.00,0.00,0.3,10.30,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759869,2,2018-01-20 18:26:03,2018-01-20 18:35:52,1,0.95,1,N,105,105,1,...,0.0,0.5,1.66,0.00,0.3,9.96,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759870,2,2018-01-20 18:36:59,2018-01-20 18:49:46,1,1.46,1,N,105,186,1,...,0.0,0.5,2.06,0.00,0.3,12.36,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759871,2,2018-01-20 23:31:09,2018-01-20 23:35:27,1,0.72,1,N,105,231,1,...,0.5,0.5,1.26,0.00,0.3,7.56,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759872,2,2018-01-31 06:40:18,2018-01-31 06:45:35,1,1.03,1,N,105,170,1,...,0.0,0.5,1.00,0.00,0.3,7.30,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759873,2,2018-01-25 00:30:29,2018-01-25 00:30:33,1,0.00,5,N,44,44,1,...,0.0,0.5,0.00,0.00,0.3,89.80,44,Staten Island,Charleston/Tottenville,Boro Zone

In [8]:
#Cleaning: Removing all the values containing unknown

mergedata_jan = df_Jan[df_Jan.Borough != 'Unknown']
mergedata_jan

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,LocationID,Borough,Zone,service_zone
0,1,2018-01-01 00:21:05,2018-01-01 00:24:23,1,0.50,1,N,41,24,2,...,0.5,0.5,0.00,0.00,0.3,5.80,41,Manhattan,Central Harlem,Boro Zone
1,2,2018-01-01 00:49:32,2018-01-01 00:59:52,1,1.36,1,N,41,74,2,...,0.5,0.5,0.00,0.00,0.3,9.80,41,Manhattan,Central Harlem,Boro Zone
2,1,2018-01-01 00:11:56,2018-01-01 00:14:35,2,0.30,1,N,41,41,2,...,0.5,0.5,0.00,0.00,0.3,5.30,41,Manhattan,Central Harlem,Boro Zone
3,1,2018-01-01 00:58:32,2018-01-01 01:43:45,1,14.10,1,N,41,112,1,...,0.5,0.5,12.10,5.76,0.3,60.66,41,Manhattan,Central Harlem,Boro Zone
4,2,2018-01-01 00:14:09,2018-01-01 00:44:06,1,8.77,1,N,41,223,1,...,0.5,0.5,6.06,0.00,0.3,36.36,41,Manhattan,Central Harlem,Boro Zone
5,2,2018-01-01 00:32:15,2018-01-01 00:35:54,1,0.76,1,N,41,151,1,...,0.5,0.5,1.00,0.00,0.3,7.30,41,Manhattan,Central Harlem,Boro Zone
6,2,2018-01-01 00:38:34,2018-01-01 00:45:19,5,1.06,1,N,41,166,1,...,0.5,0.5,1.00,0.00,0.3,8.80,41,Manhattan,Central Harlem,Boro Zone
7,1,2018-01-01 00:38:54,2018-01-01 00:52:02,1,2.40,1,N,41,244,2,...,0.5,0.5,0.00,0.00,0.3,12.80,41,Manhattan,Central Harlem,Boro Zone
8,1,2018-01-01 00:28:06,2018-01-01 00:32:34,3,1.40,1,N,41,238,1,...,0.5,0.5,2.15,0.00,0.3,9.45,41,Manhattan,Central Harlem,Boro Zone
9,1,2018-01-01 00:36:18,2018-01-01 00:41:33,3,0.90,1,N,41,42,1,...,0.5,0.5,2.00,0.00,0.3,8.80,41,Manhattan,Central Harlem,Boro Zone
10,1,2018-01-01 00:50:29,2018-01-01 01:16:19,2,10.80,1,N,41,174,2,...,0.5,0.5,0.00,0.00,0.3,33.80,41,Manhattan,Central Harlem,Boro Zone
11,1,2018-01-01 00:35:57,2018-01-01 00:45:42,2,2.90,1,N,41,239,1,...,0.5,0.5,2.35,0.00,0.3,14.15,41,Manhattan,Central Harlem,Boro Zone
12,2,2018-01-01 00:44:14,2018-01-01 01:11:50,6,11.06,1,N,41,18,2,...,0.5,0.5,0.00,2.64,0.3,37.44,41,Manhattan,Central Harlem,Boro Zone
13,1,2018-01-01 00:48:29,2018-01-01 01:15:08,4,4.80,1,N,41,229,2,...,0.5,0.5,0.00,0.00,0.3,21.30,41,Manhattan,Central Harlem,Boro Zone
14,2,2018-01-01 00:21:32,2018-01-01 00:57:10,1,8.98,1,N,41,114,1,...,0.5,0.5,6.76,0.00,0.3,40.56,41,Manhattan,Central Harlem,Boro Zone
15,1,2018-01-01 00:48:28,2018-01-01 01:00:07,1,2.00,1,N,41,168,2,...,0.5,0.5,0.00,0.00,0.3,11.80,41,Manhattan,Central Harlem,Boro Zone
16,1,2018-01-01 00:47:55,2018-01-01 00:57:58,1,2.10,1,N,41,116,2,...,0.5,0.5,0.00,0.00,0.3,10.80,41,Manhattan,Central Harlem,Boro Zone
17,1,2018-01-01 00:07:30,2018-01-01 00:16:22,3,1.40,1,N,41,151,2,...,0.5,0.5,0.00,0.00,0.3,8.80,41,Manhattan,Central Harlem,Boro Zone
18,2,2018-01-01 00:14:29,2018-01-01 00:21:52,1,1.63,1,N,41,116,1,...,0.5,0.5,1.00,0.00,0.3,9.80,41,Manhattan,Central Harlem,Boro Zone
19,2,2018-01-01 00:25:04,2018-01-01 00:31:42,5,1.22,1,N,41,42,1,...,0.5,0.5,1.56,0.00,0.3,9.36,41,Manhattan,Central Harlem,Boro Zone
20,1,2018-01-01 00:04:04,2018-01-01 00:14:45,2,2.40,1,N,41,239,2,...,0.5,0.5,0.00,0.00,0.3,11.80,41,Manhattan,Central Harlem,Boro Zone
21,1,2018-01-01 00:47:48,2018-01-01 01:01:45,1,2.70,1,N,41,143,2,...,0.5,0.5,0.00,0.00,0.3,13.30,41,Manhattan,Central Harlem,Boro Zone
22,2,2018-01-01 00:17:35,2018-01-01 00:23:23,5,1.01,1,N,41,151,1,...,0.5,0.5,1.70,0.00,0.3,9.00,41,Manhattan,Central Harlem,Boro Zone
23,2,2018-01-01 01:00:37,2018-01-01 01:08:58,1,1.72,1,N,41,42,2,...,0.5,0.5,0.00,0.00,0.3,9.30,41,Manhattan,Central Harlem,Boro Zone
24,2,2018-01-01 00:51:38,2018-01-01 00:57:32,6,1.18,1,N,41,166,2,...,0.5,0.5,0.00,0.00,0.3,7.80,41,Manhattan,Central Harlem,Boro Zone
25,1,2018-01-01 00:54:47,2018-01-01 01:04:20,1,1.60,1,N,41,42,2,...,0.5,0.5,0.00,0.00,0.3,10.30,41,Manhattan,Central Harlem,Boro Zone
26,2,2018-01-01 00:45:16,2018-01-01 00:55:10,1,2.00,1,N,41,116,1,...,0.5,0.5,0.00,0.00,0.3,10.30,41,Manhattan,Central Harlem,Boro Zone
27,2,2018-01-01 00:11:39,2018-01-01 00:17:27,2,1.24,1,N,41,74,2,...,0.5,0.5,0.00,0.00,0.3,7.80,41,Manhattan,Central Harlem,Boro Zone
28,2,2018-01-01 00:50:15,2018-01-01 00:52:46,2,0.49,1,N,41,41,2,...,0.5,0.5,0.00,0.00,0.3,5.30,41,Manhattan,Central Harlem,Boro Zone
29,1,2018-01-01 00:54:23,2018-01-01 01:03:32,2,1.50,1,N,41,74,2,...,0.5,0.5,0.00,0.00,0.3,9.80,41,Manhattan,Central Harlem,Boro Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8759844,1,2018-01-30 07:37:45,2018-01-30 07:37:52,1,0.00,1,Y,109,109,1,...,0.0,0.5,0.00,0.00,0.3,3.30,109,Staten Island,Great Kills,Boro Zone
8759845,1,2018-01-30 07:42:55,2018-01-30 07:43:42,1,0.00,5,Y,109,109,3,...,0.0,0.0,0.00,0.00,0.3,116.80,109,Staten Island,Great Kills,Boro Zone
8759846,2,2018-01-07 17:42:13,2018-01-07 17:42:36,1,0.00,5,N,115,115,1,...,0.0,0.5,15.00,0.00,0.3,240.80,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759847,2,2018-01-12 11:49:06,2018-01-12 12:10:59,1,0.43,1,N,115,115,2,...,0.0,0.5,0.00,0.00,0.3,14.30,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759848,2,2018-01-14 19:11:43,2018-01-14 19:11:58,1,0.00,5,N,115,115,1,...,0.0,0.0,0.00,0.00,0.3,130.30,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759849,2,2018-01-14 19:43:24,2018-01-14 19:45:00,2,0.00,1,N,115,115,2,...,0.0,0.5,0.00,0.00,0.3,3.80,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759850,2,2018-01-15 05:44:01,2018-01-15 05:54:36,1,6.32,1,N,115,11,2,...,0.5,0.5,0.00,0.00,0.3,20.30,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759851,2,2018-01-19 21:19:30,2018-01-19 21:28:09,5,2.90,1,N,115,214,2,...,0.5,0.5,0.00,0.00,0.3,11.80,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759852,2,2018-01-21 18:14:41,2018-01-21 19:08:32,1,0.00,1,N,115,115,1,...,0.0,0.5,8.94,0.00,0.3,38.74,115,Staten Island,Grymes Hill/Clifton,Boro Zone
8759853,2,2018-01-07 18:02:56,2018-01-07 18:03:18,1,0.19,1,N,184,184,2,...,0.0,0.5,0.00,0.00,0.3,3.30,184,Bronx,Pelham Bay Park,Boro Zone
8759854,1,2018-01-28 21:14:55,2018-01-28 21:39:54,1,14.60,1,N,184,233,4,...,0.5,0.5,0.00,0.00,0.3,41.30,184,Bronx,Pelham Bay Park,Boro Zone
8759855,2,2018-01-07 20:20:39,2018-01-07 20:20:47,1,0.00,5,N,245,245,1,...,0.0,0.0,15.06,0.00,0.3,90.36,245,Staten Island,West Brighton,Boro Zone
8759856,1,2018-01-15 14:41:58,2018-01-15 15:42:26,1,21.70,1,N,245,236,1,...,0.0,0.5,18.70,11.52,0.3,93.52,245,Staten Island,West Brighton,Boro Zone
8759857,2,2018-01-18 08:53:36,2018-01-18 09:35:51,1,13.06,1,N,245,261,1,...,0.0,0.5,0.00,17.28,0.3,59.08,245,Staten Island,West Brighton,Boro Zone
8759858,2,2018-01-20 07:38:59,2018-01-20 07:39:48,1,0.00,5,N,245,245,1,...,0.0,0.5,18.70,11.52,0.3,81.02,245,Staten Island,West Brighton,Boro Zone
8759859,1,2018-01-25 00:06:23,2018-01-25 00:06:57,1,0.00,5,N,245,245,1,...,0.0,0.0,0.00,0.00,0.3,70.30,245,Staten Island,West Brighton,Boro Zone
8759860,2,2018-01-10 01:13:21,2018-01-10 01:43:30,6,11.77,1,N,221,23,2,...,0.5,0.5,0.00,0.00,0.3,37.80,221,Staten Island,Stapleton,Boro Zone
8759861,2,2018-01-13 02:02:35,2018-01-13 02:02:43,1,0.00,3,N,27,27,2,...,0.5,0.0,0.00,0.00,0.3,20.80,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759862,2,2018-01-13 02:06:33,2018-01-13 02:10:15,1,0.97,1,N,27,27,2,...,0.5,0.5,0.00,0.00,0.3,6.80,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759863,2,2018-01-16 22:03:55,2018-01-16 22:04:25,7,0.00,5,N,27,27,1,...,0.0,0.0,15.06,0.00,0.3,90.36,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759864,2,2018-01-18 23:37:12,2018-01-18 23:46:27,1,2.14,1,N,27,264,1,...,0.5,0.5,2.06,0.00,0.3,12.36,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759865,2,2018-01-27 00:33:55,2018-01-27 00:57:10,2,7.33,1,N,27,210,2,...,0.5,0.5,0.00,2.16,0.3,26.96,27,Queens,Breezy Point/Fort Tilden/Riis Beach,Boro Zone
8759866,2,2018-01-14 10:49:13,2018-01-14 10:55:44,2,1.75,1,N,105,105,2,...,0.0,0.5,0.00,0.00,0.3,8.30,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759867,2,2018-01-14 11:54:00,2018-01-14 12:05:39,1,1.47,1,N,105,105,1,...,0.0,0.5,1.96,0.00,0.3,11.76,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759868,2,2018-01-15 17:57:10,2018-01-15 18:06:32,1,1.71,1,N,105,79,1,...,0.0,0.5,1.00,0.00,0.3,10.30,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759869,2,2018-01-20 18:26:03,2018-01-20 18:35:52,1,0.95,1,N,105,105,1,...,0.0,0.5,1.66,0.00,0.3,9.96,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759870,2,2018-01-20 18:36:59,2018-01-20 18:49:46,1,1.46,1,N,105,186,1,...,0.0,0.5,2.06,0.00,0.3,12.36,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759871,2,2018-01-20 23:31:09,2018-01-20 23:35:27,1,0.72,1,N,105,231,1,...,0.5,0.5,1.26,0.00,0.3,7.56,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759872,2,2018-01-31 06:40:18,2018-01-31 06:45:35,1,1.03,1,N,105,170,1,...,0.0,0.5,1.00,0.00,0.3,7.30,105,Manhattan,Governor's Island/Ellis Island/Liberty Island,Yellow Zone
8759873,2,2018-01-25 00:30:29,2018-01-25 00:30:33,1,0.00,5,N,44,44,1,...,0.0,0.5,0.00,0.00,0.3,89.80,44,Staten Island,Charleston/Tottenville,Boro Zone

In [9]:
#What is the most common way of payments

payment = mergedata_jan['payment_type'].value_counts().to_dict()
payment

# the most common way of payments is through Credit card(5996737)

{1: 5996737, 2: 2551208, 3: 41570, 4: 11448}

In [10]:
#Discover the way payments are executed in each borough
#initially, set that counter to 1.
mergedata_jan['COUNTER'] =1       
groupdata_jan = mergedata_jan.groupby(['payment_type','Borough'])['COUNTER'].sum() #sum function
print(groupdata_jan)

C:\Users\paavai\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

payment_type  Borough
1             Bronx               2939
              Brooklyn           63280
              EWR                  439
              Manhattan        5564803
              Queens            365207
              Staten Island         69
2             Bronx               4114
              Brooklyn           35339
              EWR                   88
              Manhattan        2356898
              Queens            154704
              Staten Island         65
3             Bronx                271
              Brooklyn            1320
              EWR                   33
              Manhattan          34240
              Queens              5697
              Staten Island          9
4             Bronx                 65
              Brooklyn             311
              EWR                   11
              Manhattan           9762
              Queens              1298
              Staten Island          1
Name: COUNTER, dtype: int64

In [ ]:
#visualize the number of payments for any possible means.

ax = mergedata_jan[['payment_type','Borough']].plot(kind='bar', title ="Comparisions", figsize=(7, 5), legend=True, fontsize=5)
ax.set_xlabel("Payment Type", fontsize=5)
ax.set_ylabel("Borough", fontsize=5)
plt.show()

In [ ]:
#To check the relationship b/w Borough & payment type

paytyp_jan=mergedata_jan['payment_type']
borough_jan=mergedata_jan['Borough']

spearmanr_coefficient,p_value=spearmanr(paytyp_jan,borough_jan)
print ('Spearman Rank Correlation Coefficient %0.3f' %(spearmanr_coefficient))

In [ ]:
#Chi-square test

table=pd.crosstab(paytyp_jan,borough_jan)

from scipy.stats import chi2_contingency

chi2, p , dof, expected=chi2_contingency(table.values)

print 'Chi-square Statistics %0.3f' % (chi2,p)

In [ ]:
#yellow cabs data - feburary
yellow_cabs_data_feb = pd.read_csv('Documents/yellow_tripdata_2018-02.csv')

In [ ]:
taxi_data = pd.read_csv("Documents/taxi _zone_lookup.csv")
taxi_data

In [ ]:
# merged data - January
merged_data_feb=pd.merge(yellow_cabs_data_feb, taxi_data, on = None, left_on = 'PULocationID', right_on = 'LocationID')
df_feb = pd.DataFrame(merged_data_feb)
df_feb

In [ ]:
#Cleaning: Removing all the values containing unknown

mergedata_feb = df_feb[df_feb.Borough != 'Unknown']
mergedata_feb

In [ ]:
#What is the most common way of payments

payment_feb = mergedata_feb['payment_type'].value_counts().to_dict()
payment_feb

In [ ]:
#Discover the way payments are executed in each borough
#initially, set that counter to 1.
mergedata_feb['COUNTER'] =1       
groupdata_feb = mergedata_feb.groupby(['payment_type','Borough'])['COUNTER'].sum() #sum function
print(groupdata_feb)

In [ ]:
#visualize the number of payments for any possible means.

ax = mergedata_feb[['payment_type','Borough']].plot(kind='bar', title ="Comparisions", figsize=(7, 5), legend=True, fontsize=5)
ax.set_xlabel("Payment Type", fontsize=5)
ax.set_ylabel("Borough", fontsize=5)
plt.show()

In [ ]:
#To check the relationship b/w Borough & payment type

paytyp_feb=mergedata_feb['payment_type']
borough_feb=mergedata_feb['Borough']

spearmanr_coefficient,p_value=spearmanr(paytyp_feb,borough_feb)
print ('Spearman Rank Correlation Coefficient %0.3f' %(spearmanr_coefficient))

In [ ]:
#Chi-square test

table=pd.crosstab(paytyp_feb,borough_feb)

from scipy.stats import chi2_contingency

chi2, p , dof, expected=chi2_contingency(table.values)

print 'Chi-square Statistics %0.3f' % (chi2,p)

In [ ]:
#yellow cabs data - march
yellow_cabs_data_mar = pd.read_csv('Documents/yellow_tripdata_2018-03.csv')

In [ ]:
taxi_data = pd.read_csv("Documents/taxi _zone_lookup.csv")
taxi_data

In [ ]:
merged_data_mar=pd.merge(yellow_cabs_data_mar, taxi_data, on = None, left_on = 'PULocationID', right_on = 'LocationID')
df_mar = pd.DataFrame(merged_data_mar)
df_mar

In [ ]:
#Cleaning: Removing all the values containing unknown

mergedata_mar = df_mar[df_mar.Borough != 'Unknown']
mergedata_mar

In [ ]:
#What is the most common way of payments

payment_mar = mergedata_mar['payment_type'].value_counts().to_dict()
payment_mar

In [ ]:
#Discover the way payments are executed in each borough
#initially, set that counter to 1.
mergedata_mar['COUNTER'] =1       
groupdata_mar = mergedata_mar.groupby(['payment_type','Borough'])['COUNTER'].sum() #sum function
print(groupdata_mar)

In [ ]:
#visualize the number of payments for any possible means.

ax = mergedata_mar[['payment_type','Borough']].plot(kind='bar', title ="Comparisions", figsize=(7, 5), legend=True, fontsize=5)
ax.set_xlabel("Payment Type", fontsize=5)
ax.set_ylabel("Borough", fontsize=5)
plt.show()

In [ ]:
#To check the relationship b/w Borough & payment type

paytyp_mar=mergedata_mar['payment_type']
borough_mar=mergedata_mar['Borough']

spearmanr_coefficient,p_value=spearmanr(paytyp_mar,borough_mar)
print ('Spearman Rank Correlation Coefficient %0.3f' %(spearmanr_coefficient))

In [ ]:
#Chi-square test

table=pd.crosstab(paytyp_mar,borough_mar)

from scipy.stats import chi2_contingency

chi2, p , dof, expected=chi2_contingency(table.values)

print 'Chi-square Statistics %0.3f' % (chi2,p)

In [ ]:
#yellow cabs data - april
yellow_cabs_data_apr = pd.read_csv('Documents/yellow_tripdata_2018-04.csv')

In [ ]:
taxi_data = pd.read_csv("Documents/taxi _zone_lookup.csv")
taxi_data

In [ ]:
merged_data_apr=pd.merge(yellow_cabs_data_apr, taxi_data, on = None, left_on = 'PULocationID', right_on = 'LocationID')
df_apr = pd.DataFrame(merged_data_apr)
df_apr

In [ ]:
#Cleaning: Removing all the values containing unknown

mergedata_apr = df_apr[df_apr.Borough != 'Unknown']
mergedata_apr

In [ ]:
#What is the most common way of payments

payment_apr = mergedata_apr['payment_type'].value_counts().to_dict()
payment_apr

In [ ]:
#Discover the way payments are executed in each borough
#initially, set that counter to 1.
mergedata_apr['COUNTER'] =1       
groupdata_apr = mergedata_apr.groupby(['payment_type','Borough'])['COUNTER'].sum() #sum function
print(groupdata_apr)

In [ ]:
#visualize the number of payments for any possible means.

ax = mergedata_apr[['payment_type','Borough']].plot(kind='bar', title ="Comparisions", figsize=(7, 5), legend=True, fontsize=5)
ax.set_xlabel("Payment Type", fontsize=5)
ax.set_ylabel("Borough", fontsize=5)
plt.show()

In [ ]:
#To check the relationship b/w Borough & payment type

paytyp_apr=mergedata_apr['payment_type']
borough_apr=mergedata_apr['Borough']

spearmanr_coefficient,p_value=spearmanr(paytyp_apr,borough_apr)
print ('Spearman Rank Correlation Coefficient %0.3f' %(spearmanr_coefficient))

In [ ]:
#Chi-square test

table=pd.crosstab(paytyp_apr,borough_apr)

from scipy.stats import chi2_contingency

chi2, p , dof, expected=chi2_contingency(table.values)

print 'Chi-square Statistics %0.3f' % (chi2,p)

In [ ]:
#yellow cabs data - may
yellow_cabs_data_may = pd.read_csv('Documents/yellow_tripdata_2018-05.csv')

In [ ]:
taxi_data = pd.read_csv("Documents/taxi _zone_lookup.csv")
taxi_data

In [ ]:
merged_data_may=pd.merge(yellow_cabs_data_may, taxi_data, on = None, left_on = 'PULocationID', right_on = 'LocationID')
df_may = pd.DataFrame(merged_data_may)
df_may

In [ ]:
#Cleaning: Removing all the values containing unknown

mergedata_may = df_may[df_may.Borough != 'Unknown']
mergedata_may

In [ ]:
#What is the most common way of payments

payment_may = mergedata_may['payment_type'].value_counts().to_dict()
payment_may

In [ ]:
#Discover the way payments are executed in each borough
#initially, set that counter to 1.
mergedata_may['COUNTER'] =1       
groupdata_may = mergedata_may.groupby(['payment_type','Borough'])['COUNTER'].sum() #sum function
print(groupdata_may)

In [ ]:
#visualize the number of payments for any possible means.

ax = mergedata_may[['payment_type','Borough']].plot(kind='bar', title ="Comparisions", figsize=(7, 5), legend=True, fontsize=5)
ax.set_xlabel("Payment Type", fontsize=5)
ax.set_ylabel("Borough", fontsize=5)
plt.show()

In [ ]:
#To check the relationship b/w Borough & payment type

paytyp_may=mergedata_may['payment_type']
borough_may=mergedata_may['Borough']

spearmanr_coefficient,p_value=spearmanr(paytyp_may,borough_may)
print ('Spearman Rank Correlation Coefficient %0.3f' %(spearmanr_coefficient))

In [ ]:
#Chi-square test

table=pd.crosstab(paytyp_may,borough_may)

from scipy.stats import chi2_contingency

chi2, p , dof, expected=chi2_contingency(table.values)

print 'Chi-square Statistics %0.3f' % (chi2,p)

In [ ]:
#yellow cabs data - june
yellow_cabs_data_june = pd.read_csv('Documents/yellow_tripdata_2018-06.csv')

In [ ]:
taxi_data = pd.read_csv("Documents/taxi _zone_lookup.csv")
taxi_data

In [ ]:
merged_data_june=pd.merge(yellow_cabs_data_june, taxi_data, on = None, left_on = 'PULocationID', right_on = 'LocationID')
df_june = pd.DataFrame(merged_data_june)
df_june

In [ ]:
#Cleaning: Removing all the values containing unknown
mergedata_june = df_june[df_june.Borough != 'Unknown']
mergedata_june

In [ ]:
#What is the most common way of payments

payment_june = mergedata_june['payment_type'].value_counts().to_dict()
payment_june

In [ ]:
#Discover the way payments are executed in each borough
#initially, set that counter to 1.
mergedata_june['COUNTER'] =1       
groupdata_june = mergedata_june.groupby(['payment_type','Borough'])['COUNTER'].sum() #sum function
print(groupdata_june)

In [ ]:
#visualize the number of payments for any possible means.

ax = mergedata_june[['payment_type','Borough']].plot(kind='bar', title ="Comparisions", figsize=(7, 5), legend=True, fontsize=5)
ax.set_xlabel("Payment Type", fontsize=5)
ax.set_ylabel("Borough", fontsize=5)
plt.show()

In [ ]:
#To check the relationship b/w Borough & payment type

paytyp_june=mergedata_june['payment_type']
borough_june=mergedata_june['Borough']

spearmanr_coefficient,p_value=spearmanr(paytyp_june,borough_june)
print ('Spearman Rank Correlation Coefficient %0.3f' %(spearmanr_coefficient))

In [ ]:
#Chi-square test

table=pd.crosstab(paytyp_june,borough_june)

from scipy.stats import chi2_contingency

chi2, p , dof, expected=chi2_contingency(table.values)

print 'Chi-square Statistics %0.3f' % (chi2,p)